version: "3.3"

services:
  jenkins:
    image: jenkins/jenkins:2.322
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:50000:50000
    volumes:
      - /srv/jenkins-master/conf:/var/jenkins-master/conf
