version: "3.3"

services:
  jenkins:
    image: jenkins-with-plugins
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:50000:50000
    environment:
      CASK_JENKINS_CONFIG: /var/jenkins_master/cacsc_configs/jenkins-config.yml

    volumes:
      - /srv/jenkins-master/conf:/var/jenkins_master/cacsc_configs
      - /srv/jenkins-master/ssl:/var/jenkins_master/ssl
