unclassified:
  location:
    url: http://10.20.30.41:8080/

jenkins:

  securityRealm:
    local:
      allowsSignup: false
      users: 
        - id: admin
          password: admin$$$
  authorizationStrategy: loggedInUsersCanDoAnything


  nodes:
  - permanent:
      launcher:
        ssh:
          credentialsId: "jenkins-agents"
          host: "10.20.30.42"
          port: 1337
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      name: "salt-node-1"
      remoteFS: "/home/jenkins"
      retentionStrategy: "always"

  # tool:
  #   git:
  #     installations:
  #       - name: git
  #         home: /usr/local/bin/git

credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "jenkins-agents"
          privateKeySource:
            directEntry:
              privateKey: "${readFile:/var/jenkins_master/cacsc_configs/agent-ssh-key}"
          scope: GLOBAL
          username: "jenkins"
