unclassified:
  location:
    url: http://10.20.30.41:8080/

jenkins:

  securityRealm:
    local:
      allowsSignup: false
      users: 
        - id: admin
          password: admin$$$
  authorizationStrategy: loggedInUsersCanDoAnything


  {% set nodes = salt['mine.get']('*agent*', 'network.ip_addrs') | dictsort() %}
  {% if nodes %}
  nodes:
  {% for server, addrs in nodes %}
  - permanent:
      launcher:
        ssh:
          credentialsId: "jenkins-agents"
          host: {{ addrs[0] }}
          port: 1337
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      name: {{ server }}
      remoteFS: "/home/jenkins"
      retentionStrategy: "always"
  {% endfor %}
  {% endif %}

# tool:
#   git:
#     installations:
#       - name: git
#         home: /usr/local/bin/git

credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "jenkins-agents"
          privateKeySource:
            directEntry:
              privateKey: "${readFile:/var/jenkins_master/ssl/agent-private-key}"
          scope: GLOBAL
          username: "jenkins"
