node {
    checkout scm
    docker.withRegistry("", "dockerLogin") {
        def jenkinsMasterImage = docker.build("thomaspturner/jenkins-with-plugins:${env.BUILD_ID}", "./jenkins-master")
        jenkinsMasterImage.push()
    }
}
