version: "3.3"

services:
  jenkins-agent:
    image: thomaspturner/jenkins-dnd-agent:latest
    privileged: true
    ports:
      - 0.0.0.0:1337:22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # TODO put this in a pillar
      - JENKINS_AGENT_SSH_PUBKEY={{ pillar['jenkins-agent']['public-key'] }}
