version: "3.3"

services:
  jenkins-agent:
    image: jenkins/ssh-agent
    ports:
      - 0.0.0.0:1337:22
    environment:
      # TODO put this in a pillar
      - JENKINS_AGENT_SSH_PUBKEY={{ pillar['jenkins-agent']['public-key'] }}
